
-- Generated by ORDS REST Data Services 23.2.3.r2421937
-- Schema: WKSP_MUSEE  Date: Tue Sep 12 02:40:26 2023 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WKSP_MUSEE',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'musee',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'musee',
      p_base_path      => '/oauth/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'musee',
      p_pattern        => 'get-token',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'musee',
      p_pattern        => 'get-token',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin
    --GET_OAUTH_TOKEN(:user_id,:password,:grant_type,:status_code,:body_text);
    GET_OAUTH_TOKEN(:body_text,:status_code);
    :cors := ''*'';
    :ct := ''application/json'';
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'musee',
      p_pattern            => 'get-token',
      p_method             => 'POST',
      p_name               => 'Access-Control-Allow-Origin',
      p_bind_variable_name => 'cors',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'musee',
      p_pattern            => 'get-token',
      p_method             => 'POST',
      p_name               => 'Content-Type',
      p_bind_variable_name => 'ct',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

    
        
COMMIT;

END;