
-- Generated by ORDS REST Data Services 23.2.3.r2421937
-- Schema: WKSP_MUSEE  Date: Tue Sep 12 02:41:27 2023 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WKSP_MUSEE',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'musee',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'util',
      p_base_path      => '/utils/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'util',
      p_pattern        => 'file',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'util',
      p_pattern        => 'file',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin
    file_upload_form;
end;');

    
        
COMMIT;

END;